apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: lugx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: aathiththan/analytics-service:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: lugx
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
