apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics-service
        image: aathiththan/analytics-service:latest   # <- Replace with your pushed image name
        ports:
        - containerPort: 3003
        env:
        - name: CLICKHOUSE_HOST
          value: "http://clickhouse:8123"
        - name: CLICKHOUSE_USER
          value: "default"
        - name: CLICKHOUSE_PASS
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
