apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: lugx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - name: game-service
        image: aathiththan/game-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: lugx
spec:
  selector:
    app: game-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
