apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: lugx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: aathiththan/order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          value: gamingdb
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: August@2015
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: lugx
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
