name: Deploy and Test

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *"  # Daily 3 AM scheduled run

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # --- DockerHub Login ---
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # --- Build & Push Images ---
    - name: Build & Push Docker Images
      run: |
        docker build -t aathiththan/lugx-frontend:latest ./frontend
        docker push aathiththan/lugx-frontend:latest

        docker build -t aathiththan/game-service:latest ./game-service
        docker push aathiththan/game-service:latest

        docker build -t aathiththan/order-service:latest ./order-service
        docker push aathiththan/order-service:latest

        docker build -t aathiththan/analytics-service:latest ./analytics-service
        docker push aathiththan/analytics-service:latest

    # --- Setup Kubectl ---
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    # --- Configure Kubernetes access ---
    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

    # --- Deploy using latest DockerHub images (Rolling Update) ---
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/frontend frontend=aathiththan/lugx-frontend:latest
        kubectl set image deployment/game-service game-service=aathiththan/game-service:latest
        kubectl set image deployment/order-service order-service=aathiththan/order-service:latest
        kubectl set image deployment/analytics-service analytics-service=aathiththan/analytics-service:latest

        # Wait for rollout completion
        kubectl rollout status deployment/frontend
        kubectl rollout status deployment/game-service
        kubectl rollout status deployment/order-service
        kubectl rollout status deployment/analytics-service

    # --- Run Integration Tests ---
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies and run tests
      run: |
        npm install
        npm test
